### ISSUE TITLE
Question about the order in DSet sequence

### ISSUE THREAD

**Issue by soloman817** [MSRCCS/Prajna#150]
Hi, I am testing Prajna today, it is very cool. But I face a strange behavior. I don't know if it is by design which I mis-understand, or if it is a bug.

First, I have two machines, both run `PrajnaClient`. So my cluster is composed by two nodes. 

I run the test from a machine called "KINGKONG", and I think it is faster because it is local. So, in the transform, I do some heavy job (like print trace log a lot) if I see this node is "KINGKONG", to slow down it. Then after that, if I call `DSet.ToIEnumerable`, I get a reversed order.

The test code is like:

```
        static void SequenceOrder(Cluster cluster)
        {
            var dset = new DSet<int> {Name = Guid.NewGuid().ToString("D"), Cluster = cluster};
            var inputs = Enumerable.Range(0, cluster.NumNodes).ToArray();
            var outputs =
                dset.Distribute(inputs)
                    .Select(x =>
                    {
                        var machineName = System.Environment.MachineName;
                        if (machineName == "KINGKONG")
                        {
                            for (var i = 0; i < 10000; ++i)
                            {
                                Trace.TraceInformation("{0}...", i);
                            }
                        }
                        return x;
                    }).ToIEnumerable().ToArray();

            Console.WriteLine("Partitions: {0}", dset.NumPartitions);

            for (var i = 0; i < inputs.Length; ++i)
            {
                Console.WriteLine("#.{0}: {1} {2}", i, inputs[i], outputs[i]);
            }
        }
```

And the output looks like:

```
Partitions: 2
#.0: 0 1
#.1: 1 0
Press any key to continue . . .
```

**Comment by msrccsbuild** [comment]
Hi, Xiang,

The behavior is by design.

When you convert a sequence to DSet, the data lost order. The reason is that during the process, a sequence of data will be partitioned, with each partition sent to different
Machine (and thread) for parallel execution. The lost of order enables these operation to be parallel executed.

It is feasible to another API to enforce order. However, the ordered API will execute much slowly. The reason is the ordered sequence will have to wait for the 1st result to be available, and then to present the 2nd result, ... The memory and execution overhead will be much higher in an ordered API than an unordered API.

If you need order for the execution result, I will suggest that you do a sort once the data arrives.

Does the above make sense to you?

Best,
Jin

**Comment by soloman817** [comment]
Thanks for the explanation, that was also my expectation.
